version: "3.8"
services:
  project_nike_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: bisma_nike
      MYSQL_PASSWORD: nike_project
      MYSQL_ROOT_PASSWORD: nike_project_root_password
      MYSQL_DATABASE: project_nike_db
    ports:
      - "4000:3306"
    volumes:
      - project_nike_volume:/var/lib/mysql

volumes:
  project_nike_volume:
    name: project_nike_volume